services:
  foundry:
    image: foundry
    container_name: foundry-crpalmer
    volumes:
      - type: bind
        source: /data/foundry
        target: /data
    ports:
      - "30000:30000"
    restart: unless-stopped

  foundry-james:
    image: foundry
    container_name: foundry-james
    volumes:
      - type: bind
        source: /data/james-foundry
        target: /data
    ports:
      - "31000:30000"
    restart: unless-stopped
